// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

package com.zhangwuji.im.protobuf;

public final class IMSwitchService {
  private IMSwitchService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMP2PCmdMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.SwitchService.IMP2PCmdMsg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    boolean hasFromUserId();
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    int getFromUserId();

    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    boolean hasToUserId();
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    int getToUserId();

    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    boolean hasCmdMsgData();
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    java.lang.String getCmdMsgData();
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    com.google.protobuf.ByteString
        getCmdMsgDataBytes();
  }
  /**
   * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
   */
  public  static final class IMP2PCmdMsg extends
      com.google.protobuf.GeneratedMessageLite<
          IMP2PCmdMsg, IMP2PCmdMsg.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.SwitchService.IMP2PCmdMsg)
      IMP2PCmdMsgOrBuilder {
    private IMP2PCmdMsg() {
      cmdMsgData_ = "";
    }
    private int bitField0_;
    public static final int FROM_USER_ID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    @java.lang.Override
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    @java.lang.Override
    public int getFromUserId() {
      return fromUserId_;
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    private void setFromUserId(int value) {
      bitField0_ |= 0x00000001;
      fromUserId_ = value;
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    private void clearFromUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromUserId_ = 0;
    }

    public static final int TO_USER_ID_FIELD_NUMBER = 2;
    private int toUserId_;
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    @java.lang.Override
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    @java.lang.Override
    public int getToUserId() {
      return toUserId_;
    }
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    private void setToUserId(int value) {
      bitField0_ |= 0x00000002;
      toUserId_ = value;
    }
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    private void clearToUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toUserId_ = 0;
    }

    public static final int CMD_MSG_DATA_FIELD_NUMBER = 3;
    private java.lang.String cmdMsgData_;
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    @java.lang.Override
    public boolean hasCmdMsgData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getCmdMsgData() {
      return cmdMsgData_;
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdMsgDataBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cmdMsgData_);
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    private void setCmdMsgData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      cmdMsgData_ = value;
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    private void clearCmdMsgData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cmdMsgData_ = getDefaultInstance().getCmdMsgData();
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    private void setCmdMsgDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      cmdMsgData_ = value.toStringUtf8();
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getCmdMsgData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getCmdMsgData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.SwitchService.IMP2PCmdMsg)
        com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsgOrBuilder {
      // Construct using com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      @java.lang.Override
      public boolean hasFromUserId() {
        return instance.hasFromUserId();
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      @java.lang.Override
      public int getFromUserId() {
        return instance.getFromUserId();
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public Builder setFromUserId(int value) {
        copyOnWrite();
        instance.setFromUserId(value);
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public Builder clearFromUserId() {
        copyOnWrite();
        instance.clearFromUserId();
        return this;
      }

      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      @java.lang.Override
      public boolean hasToUserId() {
        return instance.hasToUserId();
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      @java.lang.Override
      public int getToUserId() {
        return instance.getToUserId();
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public Builder setToUserId(int value) {
        copyOnWrite();
        instance.setToUserId(value);
        return this;
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public Builder clearToUserId() {
        copyOnWrite();
        instance.clearToUserId();
        return this;
      }

      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      @java.lang.Override
      public boolean hasCmdMsgData() {
        return instance.hasCmdMsgData();
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getCmdMsgData() {
        return instance.getCmdMsgData();
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCmdMsgDataBytes() {
        return instance.getCmdMsgDataBytes();
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder setCmdMsgData(
          java.lang.String value) {
        copyOnWrite();
        instance.setCmdMsgData(value);
        return this;
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder clearCmdMsgData() {
        copyOnWrite();
        instance.clearCmdMsgData();
        return this;
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder setCmdMsgDataBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCmdMsgDataBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.SwitchService.IMP2PCmdMsg)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasFromUserId()) {
            return null;
          }
          if (!hasToUserId()) {
            return null;
          }
          if (!hasCmdMsgData()) {
            return null;
          }
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg other = (com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg) arg1;
          fromUserId_ = visitor.visitInt(
              hasFromUserId(), fromUserId_,
              other.hasFromUserId(), other.fromUserId_);
          toUserId_ = visitor.visitInt(
              hasToUserId(), toUserId_,
              other.hasToUserId(), other.toUserId_);
          cmdMsgData_ = visitor.visitString(
              hasCmdMsgData(), cmdMsgData_,
              other.hasCmdMsgData(), other.cmdMsgData_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  bitField0_ |= 0x00000001;
                  fromUserId_ = input.readUInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  toUserId_ = input.readUInt32();
                  break;
                }
                case 26: {
                  java.lang.String s = input.readString();
                  bitField0_ |= 0x00000004;
                  cmdMsgData_ = s;
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg> parser = PARSER;
          if (parser == null) {
            synchronized (com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.SwitchService.IMP2PCmdMsg)
    private static final com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new IMP2PCmdMsg();
    }

    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMP2PCmdMsg> PARSER;

    public static com.google.protobuf.Parser<IMP2PCmdMsg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
