// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

#ifndef PROTOBUF_INCLUDED_IM_2eSwitchService_2eproto
#define PROTOBUF_INCLUDED_IM_2eSwitchService_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_IM_2eSwitchService_2eproto 

namespace protobuf_IM_2eSwitchService_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_IM_2eSwitchService_2eproto
namespace IM {
namespace SwitchService {
class IMP2PCmdMsg;
class IMP2PCmdMsgDefaultTypeInternal;
extern IMP2PCmdMsgDefaultTypeInternal _IMP2PCmdMsg_default_instance_;
}  // namespace SwitchService
}  // namespace IM
namespace google {
namespace protobuf {
template<> ::IM::SwitchService::IMP2PCmdMsg* Arena::CreateMaybeMessage<::IM::SwitchService::IMP2PCmdMsg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace IM {
namespace SwitchService {

// ===================================================================

class IMP2PCmdMsg : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:IM.SwitchService.IMP2PCmdMsg) */ {
 public:
  IMP2PCmdMsg();
  virtual ~IMP2PCmdMsg();

  IMP2PCmdMsg(const IMP2PCmdMsg& from);

  inline IMP2PCmdMsg& operator=(const IMP2PCmdMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IMP2PCmdMsg(IMP2PCmdMsg&& from) noexcept
    : IMP2PCmdMsg() {
    *this = ::std::move(from);
  }

  inline IMP2PCmdMsg& operator=(IMP2PCmdMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const IMP2PCmdMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IMP2PCmdMsg* internal_default_instance() {
    return reinterpret_cast<const IMP2PCmdMsg*>(
               &_IMP2PCmdMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(IMP2PCmdMsg* other);
  friend void swap(IMP2PCmdMsg& a, IMP2PCmdMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IMP2PCmdMsg* New() const final {
    return CreateMaybeMessage<IMP2PCmdMsg>(NULL);
  }

  IMP2PCmdMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IMP2PCmdMsg>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const IMP2PCmdMsg& from);
  void MergeFrom(const IMP2PCmdMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IMP2PCmdMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cmd_msg_data = 3;
  bool has_cmd_msg_data() const;
  void clear_cmd_msg_data();
  static const int kCmdMsgDataFieldNumber = 3;
  const ::std::string& cmd_msg_data() const;
  void set_cmd_msg_data(const ::std::string& value);
  #if LANG_CXX11
  void set_cmd_msg_data(::std::string&& value);
  #endif
  void set_cmd_msg_data(const char* value);
  void set_cmd_msg_data(const char* value, size_t size);
  ::std::string* mutable_cmd_msg_data();
  ::std::string* release_cmd_msg_data();
  void set_allocated_cmd_msg_data(::std::string* cmd_msg_data);

  // required uint32 from_user_id = 1;
  bool has_from_user_id() const;
  void clear_from_user_id();
  static const int kFromUserIdFieldNumber = 1;
  ::google::protobuf::uint32 from_user_id() const;
  void set_from_user_id(::google::protobuf::uint32 value);

  // required uint32 to_user_id = 2;
  bool has_to_user_id() const;
  void clear_to_user_id();
  static const int kToUserIdFieldNumber = 2;
  ::google::protobuf::uint32 to_user_id() const;
  void set_to_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:IM.SwitchService.IMP2PCmdMsg)
 private:
  void set_has_from_user_id();
  void clear_has_from_user_id();
  void set_has_to_user_id();
  void clear_has_to_user_id();
  void set_has_cmd_msg_data();
  void clear_has_cmd_msg_data();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cmd_msg_data_;
  ::google::protobuf::uint32 from_user_id_;
  ::google::protobuf::uint32 to_user_id_;
  friend struct ::protobuf_IM_2eSwitchService_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMP2PCmdMsg

// required uint32 from_user_id = 1;
inline bool IMP2PCmdMsg::has_from_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void IMP2PCmdMsg::set_has_from_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void IMP2PCmdMsg::clear_has_from_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void IMP2PCmdMsg::clear_from_user_id() {
  from_user_id_ = 0u;
  clear_has_from_user_id();
}
inline ::google::protobuf::uint32 IMP2PCmdMsg::from_user_id() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.from_user_id)
  return from_user_id_;
}
inline void IMP2PCmdMsg::set_from_user_id(::google::protobuf::uint32 value) {
  set_has_from_user_id();
  from_user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.from_user_id)
}

// required uint32 to_user_id = 2;
inline bool IMP2PCmdMsg::has_to_user_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void IMP2PCmdMsg::set_has_to_user_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void IMP2PCmdMsg::clear_has_to_user_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void IMP2PCmdMsg::clear_to_user_id() {
  to_user_id_ = 0u;
  clear_has_to_user_id();
}
inline ::google::protobuf::uint32 IMP2PCmdMsg::to_user_id() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.to_user_id)
  return to_user_id_;
}
inline void IMP2PCmdMsg::set_to_user_id(::google::protobuf::uint32 value) {
  set_has_to_user_id();
  to_user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.to_user_id)
}

// required string cmd_msg_data = 3;
inline bool IMP2PCmdMsg::has_cmd_msg_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IMP2PCmdMsg::set_has_cmd_msg_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IMP2PCmdMsg::clear_has_cmd_msg_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IMP2PCmdMsg::clear_cmd_msg_data() {
  cmd_msg_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cmd_msg_data();
}
inline const ::std::string& IMP2PCmdMsg::cmd_msg_data() const {
  // @@protoc_insertion_point(field_get:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  return cmd_msg_data_.GetNoArena();
}
inline void IMP2PCmdMsg::set_cmd_msg_data(const ::std::string& value) {
  set_has_cmd_msg_data();
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
#if LANG_CXX11
inline void IMP2PCmdMsg::set_cmd_msg_data(::std::string&& value) {
  set_has_cmd_msg_data();
  cmd_msg_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
#endif
inline void IMP2PCmdMsg::set_cmd_msg_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cmd_msg_data();
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
inline void IMP2PCmdMsg::set_cmd_msg_data(const char* value, size_t size) {
  set_has_cmd_msg_data();
  cmd_msg_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}
inline ::std::string* IMP2PCmdMsg::mutable_cmd_msg_data() {
  set_has_cmd_msg_data();
  // @@protoc_insertion_point(field_mutable:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  return cmd_msg_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IMP2PCmdMsg::release_cmd_msg_data() {
  // @@protoc_insertion_point(field_release:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
  if (!has_cmd_msg_data()) {
    return NULL;
  }
  clear_has_cmd_msg_data();
  return cmd_msg_data_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IMP2PCmdMsg::set_allocated_cmd_msg_data(::std::string* cmd_msg_data) {
  if (cmd_msg_data != NULL) {
    set_has_cmd_msg_data();
  } else {
    clear_has_cmd_msg_data();
  }
  cmd_msg_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd_msg_data);
  // @@protoc_insertion_point(field_set_allocated:IM.SwitchService.IMP2PCmdMsg.cmd_msg_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SwitchService
}  // namespace IM

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_IM_2eSwitchService_2eproto
