package com.zhangwuji.im.ui.widget.message;

/**
 * @author : yingmu on 15-1-8.
 * @email : yingmu@mogujie.com.
 */
public enum  RenderType {
    MESSAGE_TYPE_INVALID,
    MESSAGE_TYPE_MINE_TETX ,
    MESSAGE_TYPE_MINE_GIF ,
    MESSAGE_TYPE_MINE_IMAGE,
    MESSAGE_TYPE_MINE_GIF_IMAGE,
    MESSAGE_TYPE_MINE_AUDIO,
    MESSAGE_TYPE_MINE_BIGMOJI ,
    MESSAGE_TYPE_MINE_GIFMOJI ,
    MESSAGE_TYPE_OTHER_TEXT,
    MESSAGE_TYPE_OTHER_GIF,
    MESSAGE_TYPE_OTHER_IMAGE,
    MESSAGE_TYPE_OTHER_GIF_IMAGE,
    MESSAGE_TYPE_OTHER_AUDIO,
    MESSAGE_TYPE_OTHER_BIGMOJI,
    MESSAGE_TYPE_TIME_TITLE,
    MESSAGE_TYPE_OTHER_GIFMOJI

}
